
name: notes
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_database: ^11.3.9
  flutter_svg: ^2.0.7
  http: ^1.4.0
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^5.6.11

flutter_icons:
  android: true
  ios: true
  image_path: "/assets/images/ic_launcher_notes.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

