// File generated by FlutterFire CLI.
// ignore_for_file: unused_import, unnecessary_import, avoid_classes_with_only_static_members, ...
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLreB4S2vKAUT0f9XmYbLsGqXLq06WnY',
    appId: '1:963799132573:web:a500681d78572ae8a3a774',
    messagingSenderId: '963799132573',
    projectId: 'notes-2f4c5',
    authDomain: 'notes-2f4c5.firebaseapp.com',
    storageBucket: 'notes-2f4c5.firebasestorage.app',
    measurementId: 'G-KTSHBC3E78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgsSWIYQDQjyvrmPTAapcX-lODUS0mxG0',
    appId: '1:963799132573:android:e0db628545ee0650a3a774',
    messagingSenderId: '963799132573',
    projectId: 'notes-2f4c5',
    storageBucket: 'notes-2f4c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1NpTPpSJFBr-MBMYbXY47OG_GZMT1-FM',
    appId: '1:963799132573:ios:68cd2351b537a0bfa3a774',
    messagingSenderId: '963799132573',
    projectId: 'notes-2f4c5',
    storageBucket: 'notes-2f4c5.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1NpTPpSJFBr-MBMYbXY47OG_GZMT1-FM',
    appId: '1:963799132573:ios:68cd2351b537a0bfa3a774',
    messagingSenderId: '963799132573',
    projectId: 'notes-2f4c5',
    storageBucket: 'notes-2f4c5.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKLreB4S2vKAUT0f9XmYbLsGqXLq06WnY',
    appId: '1:963799132573:web:4e9f52d3d0492fb0a3a774',
    messagingSenderId: '963799132573',
    projectId: 'notes-2f4c5',
    authDomain: 'notes-2f4c5.firebaseapp.com',
    storageBucket: 'notes-2f4c5.firebasestorage.app',
    measurementId: 'G-Y6L9F07X76',
  );
}
